spring:
  application:
    name: architer

  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: devpassword

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  flyway:
    sql-migration-prefix: 20
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    secret-key: ac5027cd33cd1482719eeeafe46d0d1e95d07a7921e0fa11ce38310e7af6bde6
    expiration-ms: 86400000
    issuer: architer-api
    audience: architer-client

clients:
  openai:
    api-url: https://api.openai.com
    api-key: <OPENAI_API_KEY>

  minio:
    base-url: <MINIO_BASE_URL>
    access-key: <MINIO_ACCESS_KEY>
    secret-key: <MINIO_SECRET_KEY>
    bucket: <MINIO_BUCKET>
