spring:
  application:
    name: archter

  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: devuser
    password: devpassword

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  flyway:
    sql-migration-prefix: 20
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

clients:
  openai:
    api-url: https://api.openai.com
    api-key: <OPENAI_API_KEY>

  minio:
    base-url: <MINIO_BASE_URL>
    access-key: <MINIO_ACCESS_KEY>
    secret-key: <MINIO_SECRET_KEY>
    bucket: <MINIO_BUCKET>
